import { 
    FileUp, 
    Brain, 
    FileText, 
    CheckSquare, 
    Download,
    Share2
} from "lucide-react";

export default function HowItWorksSection() {
        const steps = [
                        {
                                        icon: <FileUp className="w-10 h-10 text-primary" />,
                                        title: "Upload Document",
                                        description: "Upload a PDF document via our user-friendly interface."
                        },
                        {
                                        icon: <Brain className="w-10 h-10 text-primary" />,
                                        title: "AI Analysis",
                                        description: "Our AI analyzes the document and extracts relevant information."
                        },
                        {
                                        icon: <FileText className="w-10 h-10 text-primary" />,
                                        title: "Generate Summary",
                                        description: "Our AI compiles the data and extracts the key insights, summarizing the document for you."
                        },
                        {
                                        icon: <CheckSquare className="w-10 h-10 text-primary" />,
                                        title: "Review Results",
                                        description: "Review the summary and insights generated by our AI."
                        },
                        {
                                        icon: <Download className="w-10 h-10 text-primary" />,
                                        title: "Download Summary",
                                        description: "Download the summarized document in your preferred format."
                        },
                        {
                                        icon: <Share2 className="w-10 h-10 text-primary" />,
                                        title: "Share Summary",
                                        description: "Easily share the summary with colleagues or integrate it into other systems."
                        }
        ];

        return (
                        <section className="py-16 bg-background relative">
                                        <div className="absolute inset-0 bg-gradient-to-b from-transparent to-background/50 pointer-events-none" />
                                        <div className="container max-w-6xl relative">
                                                        <div className="text-center mb-16">
                                                                        <h2 className="text-3xl font-bold mb-4">
                                                                                        How It Works
                                                                        </h2>
                                                                        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                                                                                        Discover the steps we take to ensure quality and efficiency.
                                                                        </p>
                                                        </div>
                                                        
                                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                                                                        {steps.map((item, index) => (
                                                                                        <div 
                                                                                                        key={index} 
                                                                                                        className="bg-card text-card-foreground p-8 rounded-xl shadow-lg border border-border hover:shadow-xl hover:border-primary/20 transition-all duration-300 flex flex-col items-center text-center group"
                                                                                        >
                                                                                                        <div className="mb-6 relative">
                                                                                                                        <div className="absolute -inset-3 rounded-full bg-primary/5 scale-0 group-hover:scale-100 transition-transform duration-300" />
                                                                                                                        <span className="relative">{item.icon}</span>
                                                                                                                        <div className="absolute -top-4 -right-4 w-8 h-8 rounded-full bg-primary flex items-center justify-center text-white font-bold text-sm">
                                                                                                                                        {index + 1}
                                                                                                                        </div>
                                                                                                        </div>
                                                                                                        <h3 className="text-xl font-semibold mb-3">{item.title}</h3>
                                                                                                        <p className="text-muted-foreground">{item.description}</p>
                                                                                        </div>
                                                                        ))}
                                                        </div>
                                        </div>
                        </section>
        );
}
